/*
 * TIM0_Config.h
 *
 *  Created on: Feb 5, 2023
 *      Author: Lenovo
 */

#ifndef MCAL_TIMS_INCLUDES_TIMS_CONFIG_H_
#define MCAL_TIMS_INCLUDES_TIMS_CONFIG_H_
#define TIMER0		OFF
#define TIMER1		ON
#define TIMER2		OFF
/*****************	TIMER 0		*****************/
/* Timer0 Mode Options
 * 1-TIMER0_NORMAL_MODE
 * 2-TIMER0_CTC_MODE
 * 3-TIMER0_PWM_PHASECORRECT_MODE
 * 4-TIMER0_PWM_FAST_MODE
 */
#define TIMER0_MODE		TIMER0_PWM_FAST_MODE

/*	Timer0 Prescaler Options
 * 1-TIMER0_NO_PRESCALER
 * 2-TIMER0_8_PRESCALER
 * 3-TIMER0_64_PRESCALER
 * 4-TIMER0_256_PRESCALER
 * 5-TIMER0_1024_PRESCALER
 * 6-TIMER0_EXTERNAL_SOURCE_FALLING
 * 7-TIMER0_EXTERNAL_SOURCE_RISING
 */
#define TIMER0_PRESCALER	TIMER0_256_PRESCALER

#define TIMER0_PRELOAD      212
/* OC00 PIN MODE Options in CTC MODE
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET
 */
/* OC00 PIN MODE Options in PHASE CORRECT
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET
 */
/* OC00 PIN MODE Options in FAST MODE
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET
 */
#define OC0_PIN_MODE		OC0_PIN_NON_INVERTING
#define TIMER0_CTC			156
/*****************	TIMER 1		*****************/


/* Timer1 Mode Options
 * 1-TIMER1_NORMAL_MODE
 * 2-TIMER1_CTC_MODE
 * 3-TIMER1_PWM_PHASECORRECT_MODE
 * 4-TIMER1_PWM_FAST_MODE
 */
#define TIMER1_MODE		TIMER1_PWM_FAST_MODE

/*	Timer1 Prescaler Options
 * 1-TIMER1_NO_PRESCALER
 * 2-TIMER1_8_PRESCALER
 * 3-TIMER1_64_PRESCALER
 * 4-TIMER1_256_PRESCALER
 * 5-TIMER1_1024_PRESCALER
 * 6-TIMER1_EXTERNAL_SOURCE_FALLING
 * 7-TIMER1_EXTERNAL_SOURCE_RISING
 */
#define TIMER1_PRESCALER	TIMER1_256_PRESCALER
/* TIMER1_WAVEFORM_MODE options
 * 1-TIMER1_NORMAL_WAVEFORM
 * 2-TIMER1_PHASECORRECT_8BIT
 * 3-TIMER1_PHASECORRECT_9BIT
 * 4-TIMER1_PHASECORRECT_10BIT
 * 5-TIMER1_CTC_TOP_OCR1A
 * 6-TIMER1_FASTPWM_8BIT
 * 7-TIMER1_FASTPWM_9BIT
 * 8-TIMER1_FASTPWM_10BIT
 * 9-TIMER1_PHASE_FREQ_TOP_ICR1
 * 10-TIMER1_PHASE_FREQ_TOP_OCR1A
 * 11-TIMER1_PHASECORRECT_TOP_ICR1
 * 12-TIMER1_PHASECORRECT_TOP_OCR1A
 * 13-TIMER1_CTC_TOP_ICR1
 * 14-TIMER1_FASTPWM_TOP_ICR1
 * 15-TIMER1_FASTPWM_TOP_OCR1A
 */
#define TIMER1_WAVEFORM_MODE	TIMER1_FASTPWM_TOP_ICR1

/* OC1 PIN MODE Options in non-PWM MODE
 * 1-OC1_PINS_DISCONNECTED
 * 2-OC1_PINS_TOGGLE
 * 3-OC1_PINS_CLEAR
 * 4-OC1_PINS_SET
 */
/* OC1 PIN MODE Options in PHASE CORRECT
 * 1-OC1_PINS_DISCONNECTED
 * 2-OC1_PINS_TOGGLE
 * 3-OC1_PINS_CLEAR
 * 4-OC1_PINS_SET
 */
/* OC1 PIN MODE Options in FAST MODE
 * 1-OC1_PINS_DISCONNECTED
 * 2-OC1A_PIN_TOGGLE//WGM 3:0=15//OC2B DISCONNECTED
 * 3-OC1_PINS_NONINVERTING
 * 4-OC1_PINS_INVERTING
 */
#define OC1A_PIN_MODE		OC1_PINS_NONINVERTING
#define OC1B_PIN_MODE		OC1_PINS_NONINVERTING


/*****************	TIMER 2		*****************/


/* Timer2 Mode Options
 * 1-TIMER2_NORMAL_MODE
 * 2-TIMER2_CTC_MODE
 * 3-TIMER2_PWM_PHASECORRECT_MODE
 * 4-TIMER2_PWM_FAST_MODE
 */
#define TIMER2_MODE		TIMER2_CTC_MODE

/*	Timer2 Prescaler Options
 * 1-TIMER2_NO_PRESCALER
 * 2-TIMER2_8_PRESCALER
 * 3-TIMER2_32_PRESCALER
 * 4-TIMER2_64_PRESCALER
 * 5-TIMER2_128_PRESCALER
 * 6-TIMER2_256_PRESCALER
 * 7-TIMER2_1024_PRESCALER
 */
#define TIMER2_PRESCALER	TIMER2_1024_PRESCALER

#define TIMER2_PRELOAD      212
/* OC2 PIN MODE Options in CTC MODE
 * 1-OC2_PIN_DISCONNECTED
 * 2-OC2_PIN_TOGGLE
 * 3-OC2_PIN_CLEAR
 * 4-OC2_PIN_SET
 */
/* OC20 PIN MODE Options in PHASE CORRECT
 * 1-OC2_PIN_DISCONNECTED
 * 2-OC2_PIN_PHASECORRECTPWM_NON_INVERTING
 * 4-OC2_PIN_PHASECORRECTPWM_INVERTING
 */
/* OC20 PIN MODE Options in FAST MODE
 * 1-OC2_PIN_DISCONNECTED
 * 2-OC2_PIN_FASTPWM_NON_INVERTING
 * 3-OC2_PIN_FASTPWM_INVERTING
 */
/*Calculations
 * F_PWM=F_CLK/(Pre*256)
 */
#define OC2_PIN_MODE		OC2_PIN_TOGGLE
#define TIMER2_CTC			156



#endif /* MCAL_TIMS_INCLUDES_TIMS_CONFIG_H_ */
