/*
 * LCD_Config.h
 *
 *  Created on: Sep 7, 2021
 *      Author: gerges
 */

#ifndef LCD_CONFIG_H_
#define LCD_CONFIG_H_

/*FUNCTION SET OPTIONS:
 * 1- FUNCTION_SET_8BITS_2LINES
 * 2- FUNCTION_SET_8BITS_1LINES
 * 3- FUNCTION_SET_4BITS_2LINES
 * 4- FUNCTION_SET_4BITS_1LINES
 */
#define FUNCTION_SET    FUNCTION_SET_4BITS_2LINES

/*DISPLAY ON/OFF OPTIONS:
 * 1- DISPLAY_ON_CURSOR_BLINKING
 * 2- DISPLAY_ON_CURSOR_NOBLINKING
 * 3- DISPLAY_ON_NOCURSOR
 * 4- DISPLAY_OFF
 */
#define DISPLAY_ON_OFF   DISPLAY_ON_CURSOR_BLINKING

/*ENTRY MODE SET OPTIONS:
 * 1- ENTRY_MODE_SET_INCREASE
 * 2- ENTRY_MODE_SET_DECREASE
 */
#define ENTRY_MODE_SET   ENTRY_MODE_SET_INCREASE


#define CONTROL_PORT   DIO_PORTB
#define RS   DIO_PIN1
#define RW   DIO_PIN2
#define E    DIO_PIN3

#define DATA_PORT   DIO_PORTA
#define DATA_PIN1	DIO_PIN4
#define DATA_PIN2	DIO_PIN5
#define DATA_PIN3	DIO_PIN6
#define DATA_PIN4	DIO_PIN7




#endif /* LCD_CONFIG_H_ */
