/*
 * TIM0.c
 *
 *  Created on: Feb 5, 2023
 *      Author: Lenovo
 */

#include "GPIO.h"
#include "TIMS_Types.h"
#include "TIMS_HW.h"
#include "TIMS_Config.h"

#if TIMER0==ON

static void (*TIMER0_Ptr_OVF)(void);
static void (*TIMER0_Ptr_COMP)(void);

void TIMER0_Init(void)
{
	/* Set Normal Mode */
#if TIMER0_MODE==TIMER0_NORMAL_MODE
	TIM0->TCCR0.BITS.WGM00=LOW;
	TIM0->TCCR0.BITS.WGM01=LOW;
	/* OVERFLOW INTERRUPT ENABLE */
	TIMSK->TOIE0=HIGH;

#elif TIMER0_MODE==TIMER0_CTC_MODE
	/* Set CTC Mode */
	TIM0->TCCR0.BITS.WGM00=LOW;
	TIM0->TCCR0.BITS.WGM01=HIGH;
	/* OVERFLOW INTERRUPT ENABLE */
	TIMSK->OCIE0=HIGH;
#elif TIMER0_MODE==TIMER0_PWM_PHASECORRECT_MODE
	/* Set PWM_PHASECORRECT Mode */
	TIM0->TCCR0.BITS.WGM00=HIGH;
	TIM0->TCCR0.BITS.WGM01=LOW;
	/* OVERFLOW INTERRUPT ENABLE */
	//TIMSK->OCIE0=HIGH;
#elif TIMER0_MODE==TIMER0_PWM_FAST_MODE
	/* Set PWM_FAST Mode */
	TIM0->TCCR0.BITS.WGM00=HIGH;
	TIM0->TCCR0.BITS.WGM01=HIGH;

#else
	#error"You have error in set TIMER0 MODE"
#endif
/* Set Prescaler */
	TIM0->TCCR0.ALLREG&=TIMER0_BITMASK_PRESCALER;
	TIM0->TCCR0.ALLREG|=TIMER0_PRESCALER;
	/* OC0 PINMODE */
#if OC0_PIN_MODE==OC0_PIN_DISCONNECTED
	TIM0->TCCR0.BITS.COM00=LOW;
	TIM0->TCCR0.BITS.COM01=LOW;
#elif OC0_PIN_MODE==OC0_PIN_TOGGLE
	TIM0->TCCR0.BITS.COM00=HIGH;
	TIM0->TCCR0.BITS.COM01=LOW;
#elif OC0_PIN_MODE==OC0_PIN_CLEAR
	TIM0->TCCR0.BITS.COM00=LOW;
	TIM0->TCCR0.BITS.COM01=HIGH;
#elif OC0_PIN_MODE==OC0_PIN_SET
	TIM0->TCCR0.BITS.COM00=HIGH;
	TIM0->TCCR0.BITS.COM01=HIGH;
#else
	#error"You have error in set TIMER0 MODE"
#endif
}

void TIMER0_SetPreloadValue(u8 Copy_u8Preload)
{
	TIM0->TCNT0=Copy_u8Preload;
}

void TIMER0_SetOCValue(u8 Copy_u8CTCValue)
{
	TIM0->OCR0=Copy_u8CTCValue;
}
/*
 * 								TIMER0 INTERRUPTS
 * */
void TIMER0_OVFSetCBF(void (*OVF_Fun)(void))
{
	TIMER0_Ptr_OVF=OVF_Fun;
}
void TIMER0_COMPSetCBF(void (*COMP_Fun)(void))
{
	TIMER0_Ptr_COMP=COMP_Fun;
}
void __vector_11(void)	__attribute__((signal));
void __vector_11(void)
{
	TIMER0_Ptr_OVF();
}
void __vector_10(void)	__attribute__((signal));
void __vector_10(void)
{
	TIMER0_Ptr_COMP();
}

#endif

#if TIMER1==ON

static void (*TIMER1_Ptr_OVF)(void);
static void (*TIMER1_Ptr_COMPB)(void);
static void (*TIMER1_Ptr_COMPA)(void);
static void (*TIMER1_Ptr_ICU)(void);


void TIMER1_Init(void)
{
	//Select NON-INVERTING FAST_PWM_MODE Channel A
#if   OC1A_PIN_MODE==OC1_PIN_DISCONNECTED
	TIM1->TCCR1.A.Bits.COM1A0=LOW;
	TIM1->TCCR1.A.Bits.COM1A1=LOW;
#elif OC1A_PIN_MODE==OC1_PINS_TOGGLE
	TIM1->TCCR1.A.Bits.COM1A0=HIGH;
	TIM1->TCCR1.A.Bits.COM1A1=LOW;
#elif OC1A_PIN_MODE==OC1_PINS_CLEAR
	TIM1->TCCR1.A.Bits.COM1A0=LOW;
	TIM1->TCCR1.A.Bits.COM1A1=HIGH;
#elif OC1A_PIN_MODE==OC1_PINS_SET
	TIM1->TCCR1.A.Bits.COM1A0=HIGH;
	TIM1->TCCR1.A.Bits.COM1A1=HIGH;
	#error"You have error in set TIMER1 OC1A"
#endif
#if   OC1B_PIN_MODE==OC1_PIN_DISCONNECTED
	TIM1->TCCR1.A.Bits.COM1B0=LOW;
	TIM1->TCCR1.A.Bits.COM1B1=LOW;
#elif OC1B_PIN_MODE==OC1_PINS_TOGGLE
	TIM1->TCCR1.A.Bits.COM1B0=HIGH;
	TIM1->TCCR1.A.Bits.COM1B1=LOW;
#elif OC1A_PIN_MODE==OC1_PINS_CLEAR
	TIM1->TCCR1.A.Bits.COM1B0=LOW;
	TIM1->TCCR1.A.Bits.COM1B1=HIGH;
#elif OC1A_PIN_MODE==OC1_PINS_SET
	TIM1->TCCR1.A.Bits.COM1B0=HIGH;
	TIM1->TCCR1.A.Bits.COM1B1=HIGH;
	#error"You have error in set TIMER1 OC1B"
#endif

	//Select FAST_PWM_MODE with ICR1 is TOP (l over flow bta3ak)
#if   TIMER1_WAVEFORM_MODE==TIMER1_NORMAL_WAVEFORM
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=LOW;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_PHASECORRECT_8BIT
	TIM1->TCCR1.A.Bits.WGM10=HIGH;
	TIM1->TCCR1.A.Bits.WGM11=LOW;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_PHASECORRECT_9BIT
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_PHASECORRECT_10BIT
	TIM1->TCCR1.A.Bits.WGM10=HIGH;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_CTC_TOP_OCR1A
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=LOW;
	TIM1->TCCR1.B.Bits.WGM12=HIGH;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_FASTPWM_8BIT
	TIM1->TCCR1.A.Bits.WGM10=HIGH;
	TIM1->TCCR1.A.Bits.WGM11=LOW;
	TIM1->TCCR1.B.Bits.WGM12=HIGH;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_FASTPWM_9BIT
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=HIGH;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_FASTPWM_10BIT
	TIM1->TCCR1.A.Bits.WGM10=HIGH;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=HIGH;
	TIM1->TCCR1.B.Bits.WGM13=LOW;
#elif TIMER1_WAVEFORM_MODE==TIMER1_PHASE_FREQ_TOP_ICR1
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=LOW;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=HIGH;
#elif TIMER1_WAVEFORM_MODE==TIMER1_PHASE_FREQ_TOP_OCR1A
	TIM1->TCCR1.A.Bits.WGM10=HIGH;
	TIM1->TCCR1.A.Bits.WGM11=LOW;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=HIGH;
#elif TIMER1_WAVEFORM_MODE==TIMER1_PHASECORRECT_TOP_ICR1
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=HIGH;
#elif TIMER1_WAVEFORM_MODE==TIMER1_PHASECORRECT_TOP_OCR1A
	TIM1->TCCR1.A.Bits.WGM10=HIGH;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=LOW;
	TIM1->TCCR1.B.Bits.WGM13=HIGH;
#elif TIMER1_WAVEFORM_MODE==TIMER1_CTC_TOP_ICR1
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=LOW;
	TIM1->TCCR1.B.Bits.WGM12=HIGH;
	TIM1->TCCR1.B.Bits.WGM13=HIGH;
#elif TIMER1_WAVEFORM_MODE==TIMER1_FASTPWM_TOP_ICR1
	TIM1->TCCR1.A.Bits.WGM10=LOW;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=HIGH;
	TIM1->TCCR1.B.Bits.WGM13=HIGH;
#elif TIMER1_WAVEFORM_MODE==TIMER1_FASTPWM_TOP_OCR1A
	TIM1->TCCR1.A.Bits.WGM10=HIGH;
	TIM1->TCCR1.A.Bits.WGM11=HIGH;
	TIM1->TCCR1.B.Bits.WGM12=HIGH;
	TIM1->TCCR1.B.Bits.WGM13=HIGH;
#else
	#error"You have error in set TIMER1 Waveform"
#endif
#if   TIMER1_PRESCALER ==TIMER1_NO_PRESCALER
	TIM1->TCCR1.B.Bits.CS10=HIGH;
	TIM1->TCCR1.B.Bits.CS11=LOW;
	TIM1->TCCR1.B.Bits.CS12=LOW;
#elif TIMER1_PRESCALER ==TIMER1_8_PRESCALER	//Prescaler 8
	TIM1->TCCR1.B.Bits.CS10=LOW;
	TIM1->TCCR1.B.Bits.CS11=HIGH;
	TIM1->TCCR1.B.Bits.CS12=LOW;
#elif TIMER1_PRESCALER ==TIMER1_64_PRESCALER
	TIM1->TCCR1.B.Bits.CS10=HIGH;
	TIM1->TCCR1.B.Bits.CS11=HIGH;
	TIM1->TCCR1.B.Bits.CS12=LOW;
#elif TIMER1_PRESCALER ==TIMER1_256_PRESCALER
	TIM1->TCCR1.B.Bits.CS10=LOW;
	TIM1->TCCR1.B.Bits.CS11=LOW;
	TIM1->TCCR1.B.Bits.CS12=HIGH;
#elif TIMER1_PRESCALER ==TIMER1_1024_PRESCALER
	TIM1->TCCR1.B.Bits.CS10=HIGH;
	TIM1->TCCR1.B.Bits.CS11=LOW;
	TIM1->TCCR1.B.Bits.CS12=HIGH;
#elif TIMER1_PRESCALER ==TIMER1_EXTERNAL_SOURCE_FALLING
	TIM1->TCCR1.B.Bits.CS10=LOW;
	TIM1->TCCR1.B.Bits.CS11=HIGH;
	TIM1->TCCR1.B.Bits.CS12=HIGH;
#elif TIMER1_PRESCALER ==TIMER1_EXTERNAL_SOURCE_RISING
	TIM1->TCCR1.B.Bits.CS10=HIGH;
	TIM1->TCCR1.B.Bits.CS11=HIGH;
	TIM1->TCCR1.B.Bits.CS12=HIGH;
#else
	#error"You have error in set TIMER1 Prescaler"
#endif
}

void TIMER1_SetCompareA(u16 Copy_u16CTCValue)
{
	TIM1->OCR1A=Copy_u16CTCValue;
}
void TIMER1_SetCompareB(u16 Copy_u16CTCValue)
{
	TIM1->OCR1B=Copy_u16CTCValue;
}

void TIMER1_SetTopValue(u16 Copy_u16TopValue)
{
	TIM1->ICR1=Copy_u16TopValue;
}


/*
 * 								TIMER1 INTERRUPTS
 * */
void TIMER1_OVFSetCBF(void (*OVF_Fun)(void))
{
	TIMER1_Ptr_OVF=OVF_Fun;
}
void TIMER1_COMPBSetCBF(void (*COMPB_Fun)(void))
{
	TIMER1_Ptr_COMPB=COMPB_Fun;
}
void TIMER1_COMPASetCBF(void (*COMPA_Fun)(void))
{
	TIMER1_Ptr_COMPA=COMPA_Fun;
}
void TIMER1_ICUSetCBF(void (*ICU_Fun)(void))
{
	TIMER1_Ptr_ICU=ICU_Fun;
}

void __vector_9(void)	__attribute__((signal));
void __vector_9(void)
{
	TIMER1_Ptr_OVF();
}
void __vector_8(void)	__attribute__((signal));
void __vector_8(void)
{
	TIMER1_Ptr_COMPB();
}
void __vector_7(void)	__attribute__((signal));
void __vector_7(void)
{
	TIMER1_Ptr_COMPA();
}
void __vector_6(void)	__attribute__((signal));
void __vector_6(void)
{
	TIMER1_Ptr_ICU();
}

#endif

#if TIMER2==ON

static void (*TIMER2_Ptr_OVF)(void);
static void (*TIMER2_Ptr_COMP)(void);

void TIMER2_voidInit(void)
{

	/* Set Normal Mode */
#if TIMER2_MODE==TIMER2_NORMAL_MODE
	TIM2->TCCR2.BITS.WGM20=LOW;
	TIM2->TCCR2.BITS.WGM21=LOW;
	/* OVERFLOW INTERRUPT ENABLE */
	TIMSK->TOIE2=HIGH;

#elif TIMER2_MODE==TIMER2_CTC_MODE
	/* Set CTC Mode */
	TIM2->TCCR2.BITS.WGM20=LOW;
	TIM2->TCCR2.BITS.WGM21=HIGH;
	/* OVERFLOW INTERRUPT ENABLE */
	TIMSK->OCIE2=HIGH;
#elif TIMER2_MODE==TIMER2_PWM_PHASECORRECT_MODE
	/* Set PWM_PHASECORRECT Mode */
	TIM2->TCCR2.BITS.WGM20=HIGH;
	TIM2->TCCR2.BITS.WGM21=LOW;
	/* OVERFLOW INTERRUPT ENABLE */
	TIMSK->OCIE2=HIGH;
#elif TIMER2_MODE==TIMER2_PWM_FAST_MODE
	/* Set PWM_FAST Mode */
	TIM2->TCCR2.BITS.WGM20=HIGH;
	TIM2->TCCR2.BITS.WGM21=HIGH;

#else
	#error"You have error in set TIMER0 MODE"
#endif
/* Set Prescaler */
	TIM2->TCCR2.ALLREG&=TIMER2_BITMASK_PRESCALER;
	TIM2->TCCR2.ALLREG|=TIMER2_PRESCALER;
	/* OC0 PINMODE */
#if OC2_PIN_MODE==OC2_PIN_DISCONNECTED
	TIM2->TCCR2.BITS.COM20=LOW;
	TIM2->TCCR2.BITS.COM21=LOW;
#elif OC2_PIN_MODE==OC2_PIN_TOGGLE
	TIM2->TCCR2.BITS.COM20=HIGH;
	TIM2->TCCR2.BITS.COM21=LOW;
#elif OC2_PIN_MODE==OC2_PIN_CLEAR
	TIM2->TCCR2.BITS.COM20=LOW;
	TIM2->TCCR2.BITS.COM21=HIGH;
#elif OC2_PIN_MODE==OC2_PIN_SET
	TIM2->TCCR2.BITS.COM20=HIGH;
	TIM2->TCCR2.BITS.COM21=HIGH;
#else
	#error"You have error in set TIMER0 MODE"
#endif
}

void TIMER2_voidSetPreloadValue(u8 Copy_u8Preload)
{
	TIM2->TCNT2=Copy_u8Preload;
}

void TIMER2_voidSetCTCValue(u8 Copy_u8CTCValue)
{
	TIM2->OCR2=Copy_u8CTCValue;
}
/*
 * 								TIMER2 INTERRUPTS
 * */
void TIMER2_OVFSetCBF(void (*OVF_Fun)(void))
{
	TIMER2_Ptr_OVF=OVF_Fun;
}
void TIMER2_COMPSetCBF(void (*COMP2_Fun)(void))
{
	TIMER2_Ptr_COMP=COMP2_Fun;
}
void __vector_5(void)	__attribute__((signal));
void __vector_5(void)
{
	TIMER2_Ptr_OVF();
}
void __vector_4(void)	__attribute__((signal));
void __vector_4(void)
{
	TIMER2_Ptr_COMP();
}




#endif




